name: Vulnerable Action

on:
  push:
    branches:
      - master

jobs:
  get-secret:
    name: Get Some Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Directory Listing
        run: |
          ls -al
          ls /
          pwd
          id
          cat /etc/passwd
