name: Vulnerable Action

on:
  push:
    branches:
      - master

jobs:
  run_commands:
    name: Run Linux Commands
    runs-on: ubuntu-latest
    steps:
      - name: Directory Listing
        run: |
          ls -al
          ls /
          pwd
          id
          cat /etc/passwd
          
  get_secrets:
    name: Get Some Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Get Secret
        run: |
          echo "$ALLMYSECRETS"
          echo "$ALLMYVARS"
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
