name: Vulnerable Action

on:
  push:
    branches:
      - master

jobs:
  run_commands:
    name: Run Linux Commands
    runs-on: ubuntu-latest
    steps:
      - name: Directory Listing
        run: |
          ls -al
          ls /
          pwd
          id
          cat /etc/passwd
          
  get_secrets:
    name: Get Some Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get Secret
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
          SUPER_SECRET: ${{ secrets.DVWA_SECRET_KEY }}
        run: |
          ls
          echo "$SUPER_SECRET"
          echo "$SUPER_SECRET" > secret_file
          cat secret_file
          echo "$ALLMYSECRETS"
          echo "$ALLMYVARS"
